### ISSUE TITLE
The d3dx12.h file in master is not compatible with 10.0.10586.0

### ISSUE THREAD

**Issue by aguaviva** [Microsoft/DirectXTK12#5]
The file d3dx12.h references a "D3D12_DESCRIPTOR_RANGE1" structure that is not defined in 10.0.10586.0

Thanks for such a good lib :)

**Comment by walbourn** [comment]
This is by design. My GitHub projects now require the Windows 10 Anniversary Update SDK (14393) to build (all the vcxproj files are now set to use it). For UWP you can still set the "Minimum Target Version" to 10586 to support the Windows 10 November 2015 update. There's no reason to use 10240 as essentially everyone has upgraded.
